# =========================
# MYSQL
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/billing-db?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
# =========================
# HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
# =========================
# HIKARI
# =========================
spring.datasource.hikari.pool-name=MySQLPool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
# =========================
# Log des requêtes
# =========================
logging.level.org.hibernate.SQL=DEBUG
# Log des paramètres (TRÈS IMPORTANT)
logging.level.org.hibernate.type.descriptor.sql=TRACE
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
