services:
  # =========================================================================
  #  SINGLE DATABASE SERVER
  # =========================================================================
  billing-db:
    image: mysql:8.0
    container_name: billing-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_global_data:/var/lib/mysql
    networks:
      - sbatec-net
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================================================================
  # PHPMYADMIN
  # =========================================================================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      billing-db:
        condition: service_healthy
    environment:
      PMA_HOST: billing-db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - sbatec-net

  # =========================================================================
  # DISCOVERY (EUREKA)
  # =========================================================================
  discovery-service:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    container_name: discovery-service
    restart: unless-stopped
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
    networks:
      - sbatec-net
  # =========================================================================
  # GATEWAY
  # =========================================================================
  gateway-service:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8181:8181"
      - "5001:5001"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001
      - SPRING_APPLICATION_NAME=gateway
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - JWK_SET_URL=http://authent-service:3000/api/public-key/jwks.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8181/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - sbatec-net
  # =========================================================================
  # AUTHENT SERVICE
  # =========================================================================
  authent-service:
    build:
      context: .
      dockerfile: authent/Dockerfile
    container_name: authent-service
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5002:5002"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
      - SPRING_APPLICATION_NAME=authent
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://billing-db:3306/user-db?serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
    depends_on:
      billing-db:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - sbatec-net

  # =========================================================================
  # COMPANY SERVICE
  # =========================================================================
  company-service:
    build:
      context: .
      dockerfile: company/Dockerfile
    container_name: company-service
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5003:5003"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5003
      - JWK_SET_URL=http://authent-service:3000/api/public-key/jwks.json
      - SPRING_APPLICATION_NAME=company
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://billing-db:3306/company-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
    depends_on:
      billing-db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - sbatec-net

    # =========================================================================
    # PRESTATION SERVICE
    # =========================================================================
  prestation-service:
    build:
      context: .
      dockerfile: prestation/Dockerfile
    container_name: prestation-service
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "5004:5004"
    environment:
      - SPRING_APPLICATION_NAME=prestation
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5004
      - JWK_SET_URL=http://authent-service:3000/api/public-key/jwks.json
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://billing-db:3306/prestation-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
    depends_on:
      billing-db:
        condition: service_healthy
      discovery-service:
        condition: service_started

    networks:
      - sbatec-net
  # =========================================================================
  # CLIENT SERVICE
  # =========================================================================
  client-service:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client-service
    restart: unless-stopped
    ports:
      - "7000:7000"
      - "5005:5005"
    environment:
      - SPRING_APPLICATION_NAME=client
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - JWK_SET_URL=http://authent-service:3000/api/public-key/jwks.json
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://billing-db:3306/client-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
    depends_on:
      billing-db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - sbatec-net

  # =========================================================================
  # CONSULTANT SERVICE
  # =========================================================================
  consultant-service:
    build:
      context: .
      dockerfile: consultant/Dockerfile
    container_name: consultant-service
    restart: unless-stopped
    ports:
      - "6000:6000"
      - "5006:5006"
    environment:
      - SPRING_APPLICATION_NAME=consultant
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
      - JWK_SET_URL=http://authent-service:3000/api/public-key/jwks.json
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://billing-db:3306/consultant-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
    depends_on:
      billing-db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - sbatec-net
  # =========================================================================
  # FACTURE SERVICE
  # =========================================================================
  facture-service:
    build:
      context: .
      dockerfile: facture/Dockerfile
    container_name: facture-service
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5007:5007"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
      - JWK_SET_URL=http://authent-service:3000/api/public-key/jwks.json
      - SPRING_APPLICATION_NAME=facture
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://billing-db:3306/facture-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_BCC=${MAIL_BCC}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
    volumes:
      - C:/temp/pdf:/data/pdf
      - C:/temp/csv:/data/csv
      - C:/temp/libelles:/data/libelle-facture
    depends_on:
      billing-db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - sbatec-net
  # =========================================================================
  # ANGULAR FRONTEND
  # =========================================================================
  front-service:
    build:
      context: ../bill-front-ng
    image: billing-api-ms-front-service
    container_name: front-service
    restart: unless-stopped
    ports:
      - "4202:80"
    networks:
      - sbatec-net

# =========================================================================
# CONFIGURATIONS GLOBALES
# =========================================================================
volumes:
  mysql_global_data:

networks:
  sbatec-net:
    driver: bridge