# =========================================================================
# SERVICE DISCOVERY (EUREKA)
# =========================================================================
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
# Active la création automatique des routes via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
# Force la Gateway à chercher les noms de services en minuscules dans l'URL
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
# Dit à Eureka de renouveler son statut toutes les 3 secondes
eureka.instance.lease-renewal-interval-in-seconds=3
# Dit à Eureka d'expirer le pod s'il n'a pas donné de signe de vie après 5 secondes
eureka.instance.lease-expiration-duration-in-seconds=5
# =========================
# CONFIG
# =========================
#spring.cloud.config.enabled=false
#spring.cloud.config.import-check.enabled=false
#spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
# =========================================================================
# 1. CONNEXION BBD (PORT 3306 COMPATIBLE K8S / DEV LOCAL VIA ENV)
# =========================================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://billing-db:3307/facture-db?serverTimezone=UTC&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_pass}
# =========================================================================
# 2. STRATÉGIE DE BASE DE DONNÉES (FLYWAY UNIQUE, HIBERNATE PASSIF)
# =========================================================================
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
# =========================================================================
# 3. LOGS INDISPENSABLES (TRACE FLYWAY + REQUÊTES SQL BRUTES ET VALEURS)
# =========================================================================
logging.level.org.flywaydb=DEBUG
spring.jpa.show-sql=false
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# =========================
# PARAMETRES (Adaptés pour Linux/Kubernetes)
# =========================
app.mail-from=${MAIL_FROM}
app.mail-bcc=${MAIL_BCC}
app.smtp-username=${MAIL_USERNAME}
app.smtp-password=${MAIL_PASSWORD}
app.smtp-host=smtp.free.fr
app.smtp-port=587
app.path-libelle-facture=Facture Client
app.path-libelle-charges=Charges
app.path-libelle-releve=Relevé de compte
app.fichier-suivi-factures=suivi-facturation.xls
app.path-file-pdf=/tmp/pdf
app.fichier-import-csv=/tmp/csv
# =========================================================================
# 4. SÉCURITÉ ACTUATOR (INDISPENSABLE POUR KUBERNETES)
# =========================================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always