apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authent-service
  name: authent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authent-service
  template:
    metadata:
      labels:
        app: authent-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: SPRING_APPLICATION_NAME
              value: "authent"
            - name: SPRING_DATASOURCE_PASSWORD
              value: app_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://billing-db:3307/user-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
          image: authent-service
          imagePullPolicy: Never
          # =========================================================================
          # REMPLACEMENT DU CURL PAR LE HTTPGET NATIF KUBERNETES
          # =========================================================================
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          name: authent-service
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authent-service
  name: authent-service
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: authent-service