apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-service
  name: company-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker" # <--- Active application-docker.properties
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: SPRING_APPLICATION_NAME
              value: "company"
            - name: SPRING_DATASOURCE_PASSWORD
              value: app_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://billing-db:3307/company-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
          image: company-service
          imagePullPolicy: Never
          name: company-service
          ports:
            - containerPort: 5000
              protocol: TCP

          # ============================================================
          # SONDE DE DÉMARRAGE CORRIGÉE (HTTPGET SANS CURL)
          # ============================================================
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          # ============================================================
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: company-service
  name: company-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: company-service