apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consultant-service
  name: consultant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultant-service
  template:
    metadata:
      labels:
        app: consultant-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker" # <--- Active application-docker.properties (port 6000)
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: SPRING_APPLICATION_NAME
              value: "consultant"
            - name: SPRING_DATASOURCE_PASSWORD
              value: app_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://billing-db:3307/consultant-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
          image: consultant-service
          imagePullPolicy: Never
          name: consultant-service
          ports:
            - containerPort: 6000
              protocol: TCP

          # ============================================================
          # SONDE DE DÉMARRAGE CORRIGÉE (HTTPGET SANS CURL)
          # ============================================================
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 6000
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          # ============================================================
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: consultant-service
  name: consultant-service
spec:
  ports:
    - name: "6000"
      port: 6000
      targetPort: 6000
  selector:
    app: consultant-service