apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: facture-service
  name: facture-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facture-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: facture-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker" # <--- Active application-docker.properties (port 8000)
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: FICHIER_IMPORT_CSV
              value: /data/csv/import.csv
            - name: FICHIER_SUIVI_NAME
              value: suivi_factures.csv
            - name: SAVE_FILE_LOCAL_DISQUE
              value: "true"
            - name: SPRING_APPLICATION_NAME
              value: "facture"
            - name: SPRING_DATASOURCE_PASSWORD
              value: app_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://billing-db:3307/facture-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
            - name: STORAGE_PATHROOT_LIBELLE_CHARGES
              value: /data/libelle-charges
            - name: STORAGE_PATHROOT_LIBELLE_FACTURE
              value: /data/libelle-facture
            - name: STORAGE_PATHROOT_LIBELLE_RELEVE
              value: /data/libelle-releve
            - name: STORAGE_PATHROOT_PDF
              value: /data/pdf
          image: facture-service
          imagePullPolicy: Never
          name: facture-service
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /data/pdf
              name: volume-pdf
            - mountPath: /data/csv
              name: volume-csv
            - mountPath: /data/libelle-facture
              name: volume-libelles

          # ============================================================
          # SONDE DE DÉMARRAGE CORRIGÉE (HTTPGET SANS CURL)
          # ============================================================
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          # ============================================================

      restartPolicy: Always
      volumes:
        - name: volume-pdf
          emptyDir: { }
        - name: volume-csv
          emptyDir: { }
        - name: volume-libelles
          emptyDir: { }

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: facture-service
  name: facture-service
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: facture-service