spring.application.name=eureka-server
server.port=8761
# Eureka Server ne doit pas s'enregistrer lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Optionnel (UI dashboard)
eureka.server.enable-self-preservation=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

