spring.application.name=discovery
server.port=8761
# Eureka Server ne doit pas s'enregistrer lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Désactive complètement les tentatives de réplication entre pairs
eureka.server.enable-peer-replication=false
# Optionnel (UI dashboard)
eureka.server.enable-self-preservation=false
# Nettoie les instances mortes toutes les 5 secondes (au lieu de 60s)
eureka.server.eviction-interval-timer-in-ms=5000
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

